### ISSUE TITLE
无法查看中文文档

### ISSUE THREAD

**Issue by yibie** [yuchen-lea/org-noter-plus#1]
点击超链接，跳转了一个页面之后，再点击超链接，无法跳转。

**Comment by yuchen-lea** [comment]
应该与中文文档无关，请提供更具体的信息
1. 贴出具体的链接，例如  `[[nov:/Users/yuchen/Books/Kelly McGonigal/Zi Kong Li (280)/Zi Kong Li - Kelly McGonigal.epub::6:1][为了成功做到自控，你必须知道自己为何失败]]` 或者  `[[pdf:/Users/yuchen/Books/Leften Stavros Stavrianos/Quan Qiu Tong Shi _1500Nian Yi Qian (7783)/Quan Qiu Tong Shi _1500Nian Yi - Leften Stavros Stavrianos.pdf::85][第一编  文明之前的人类]]`
2. 再点击超链接之后的提示信息

**Comment by yibie** [comment]
抱歉，我是指 GitHub 项目页面上的超链接「中文文档」，点击之后，无法跳转

**Comment by yuchen-lea** [comment]
啊哈，了解！感谢反馈。犯了低级错误，已经解决 😂
