### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by hongfei6** [yuchen-lea/org-noter-plus#5]
初步尝试了一下，M-x org-noter-plus-create-skeleton-list，没有内容输出 提示"End of file during parsing: …/.emacs.d/…/org-noter-plus.el" 请问可能是什么原因呢？
我是按doomemacs方式安装的，安装过程没有报错

谢谢

**Comment by yuchen-lea** [comment]
抱歉，应该是reformat的时候出错了，现在试试看？
