### ISSUE TITLE
Symbol's value as variable is void: session

### ISSUE THREAD

**Issue by vizmoe** [yuchen-lea/org-noter-plus#6]
After start org-noter session and M-x org-noter-plus-creat-skeleton-list, it returns the following messages:

Symbol’s value as variable is void: session
funcall-interactively: Symbol’s value as variable is void: session

**Comment by yuchen-lea** [comment]
Sorry for the late reply，It's my first eslip package and there're many things to improve.
Fetch the newest version and have a try, it should be fixed now.
Let me know if you have any problem.

**Comment by vizmoe** [comment]
Thanks for your effort!
